name: build main gpu


on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:


jobs:


  linux-intel-cu12x:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cuda-version: ['126', '128']
        python-version: ['3.11', '3.12', '3.13', '3.14']
    steps:
      - name: Free disk space
        run: |
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/share/powershell
          sudo rm -rf /usr/local/share/chromium
          docker system prune -af
      - uses: actions/checkout@v6
      - name: Build wheel cu${{ matrix.cuda-version }}
        env:
          CUDA_VERSION: ${{ matrix.cuda-version }}
          BUILD_IMAGE: ratharog/manylinux_2_28_x86_64:cu${{ matrix.cuda-version }}
          BUILD_PYTHON_VERSIONS: "['${{ matrix.python-version }}']"
        if: |
          (github.event_name == 'push' && startsWith(github.ref, 'refs/tags') && env.CUDA_VERSION != '') || 
          env.CUDA_VERSION == '128'
        run: |
          # clone nvidia cuda cccl to cumm/third_party/cccl
          # ctk-cccl mapping: https://github.com/NVIDIA/cccl#mapping-to-ctk-versions
          if [ -n "$CUDA_VERSION" ]; then
            if [ "$CUDA_VERSION" = "126" ]; then
              CCCL_BRANCH_NAME="2.5.0"
            elif [ "$CUDA_VERSION" = "128" ]; then
              CCCL_BRANCH_NAME="2.7.0"
            elif [ "$CUDA_VERSION" = "129" ]; then
              CCCL_BRANCH_NAME="2.8.5"
            else
              echo "Unexpected CUDA_VERSION: $CUDA_VERSION"
              exit 1
            fi
            git clone https://github.com/NVIDIA/cccl.git third_party/cccl -b v$CCCL_BRANCH_NAME
          fi
          docker run --rm \
            -e CUMM_CUDA_VERSION="$CUDA_VERSION" \
            -e BUILD_PYTHON_VERSIONS="$BUILD_PYTHON_VERSIONS" \
            -v "$(pwd)":/io \
            $BUILD_IMAGE \
            bash -c "source /etc/bashrc && /io/tools/build-wheels.sh"
      - name: Archive wheels
        uses: actions/upload-artifact@v7
        with:
          name: linux-intel-cu${{ matrix.cuda-version }}-py${{ matrix.python-version }}
          path: dist/*.whl

  linux-intel-cu13x:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cuda-version: ['130']
        python-version: ['3.11', '3.12', '3.13', '3.14']
    steps:
      - name: Free disk space
        run: |
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/share/powershell
          sudo rm -rf /usr/local/share/chromium
          docker system prune -af
      - uses: actions/checkout@v6
      - name: Build wheel cu${{ matrix.cuda-version }}
        env:
          CUDA_VERSION: ${{ matrix.cuda-version }}
          BUILD_IMAGE: ratharog/manylinux_2_28_x86_64:cu${{ matrix.cuda-version }}
          BUILD_PYTHON_VERSIONS: "['${{ matrix.python-version }}']"
        if: |
          (github.event_name == 'push' && startsWith(github.ref, 'refs/tags') && env.CUDA_VERSION != '') || 
          env.CUDA_VERSION == '130'
        run: |
          # clone nvidia cuda cccl to cumm/third_party/cccl
          # ctk-cccl mapping: https://github.com/NVIDIA/cccl#mapping-to-ctk-versions
          if [ -n "$CUDA_VERSION" ]; then
            if [ "$CUDA_VERSION" = "130" ]; then
              CCCL_BRANCH_NAME="3.0.3"
            elif [ "$CUDA_VERSION" = "131" ]; then
              CCCL_BRANCH_NAME="3.1.4"
            elif [ "$CUDA_VERSION" = "132" ]; then
              CCCL_BRANCH_NAME="3.2.1"
            else
              echo "Unexpected CUDA_VERSION: $CUDA_VERSION"
              exit 1
            fi
            git clone https://github.com/NVIDIA/cccl.git third_party/cccl -b v$CCCL_BRANCH_NAME
          fi
          docker run --rm \
            -e CUMM_CUDA_VERSION="$CUDA_VERSION" \
            -e BUILD_PYTHON_VERSIONS="$BUILD_PYTHON_VERSIONS" \
            -v "$(pwd)":/io \
            $BUILD_IMAGE \
            bash -c "source /etc/bashrc && /io/tools/build-wheels.sh"
      - name: Archive wheels
        uses: actions/upload-artifact@v7
        with:
          name: linux-intel-cu${{ matrix.cuda-version }}-py${{ matrix.python-version }}
          path: dist/*.whl

  windows-intel-all:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.11', '3.12', '3.13', '3.14'] 
        cuda-version: ['12.6', '12.8', '13.0']
    steps:
      - uses: actions/checkout@v6
      - name: Install CUDA
        env:
          CUDA_VERSION: ${{ matrix.cuda-version }}
          PYTHON_VERSION: ${{ matrix.python-version }}
          cuda: ${{ matrix.cuda-version }}
        if: |
          env.CUDA_VERSION != '' && (
            (github.event_name == 'push' && startsWith(github.ref, 'refs/tags')) || 
            env.PYTHON_VERSION == '3.14'
          )
        shell: powershell
        run: .\tools\install_windows_cuda.ps1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Install pep build
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build wheel setuptools
      - name: Build wheel
        env:
          CUDA_VERSION: ${{ matrix.cuda-version }}
          PYTHON_VERSION: ${{ matrix.python-version }}
          CUMM_CUDA_VERSION: ${{ matrix.cuda-version }}
        if: |
          (github.event_name == 'push' && startsWith(github.ref, 'refs/tags')) || 
          env.PYTHON_VERSION == '3.14'
        run: |
          # clone nvidia cuda cccl to cumm/third_party/cccl
          # ctk-cccl mapping: https://github.com/NVIDIA/cccl#mapping-to-ctk-versions
          if ($env:CUDA_VERSION -ne '') {
            $CCCL_BRANCH_NAME = switch ($env:CUDA_VERSION) {
              "12.6" { "2.5.0"; break }
              "12.8" { "2.7.0"; break }
              "13.0" { "3.0.3"; break }
              "13.1" { "3.1.4"; break }
              "13.2" { "3.2.1"; break }
              default { Write-Error "Unexpected CUDA_VERSION: $($env:CUDA_VERSION)"; exit 1 }
            }
            git clone https://github.com/NVIDIA/cccl.git third_party/cccl -b v$CCCL_BRANCH_NAME
            $env:CUMM_CUDA_ARCH_LIST = "all"
          }
          # if we use $env to set a var with empty string, this env will be deteted. f**k windows x2 !
          $env:CUMM_DISABLE_JIT = "1"
          python -m pip install pccm pybind11
          python -m build --wheel --outdir dist/ .
        shell: powershell
      - name: Archive wheels
        uses: actions/upload-artifact@v7
        with:
          name: windows-intel-cu${{ matrix.cuda-version }}-py${{ matrix.python-version }}
          path: dist/*.whl
